//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockPaperScissors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Winner
    {
        public int WinnerId { get; set; }
        public string Name { get; set; }
        public int Score { get; set; }
        public string Self { get; set; }
    }
}
